### PR TITLE
Fix convert_to_tag for the case of str is nil

### LINKED ISSUE #262: undefined method error occurred when "remove tag" is executed with no arguments
VERSION
0.51（ruby 2.6.0）

SUMMARY
When "remove tag" is executed with no arguments,  the following error messages are output.
```
$friends remove tag
Error: undefined method `strip' for nil:NilClass
```

When "remove nickname”, the error messages are as below.
```
$friends remove nickname
Error: No friend found for ""
```

I think it would be better to output "Error: No friend found for" message in the case of "remove tag" as well. 👍

### PR DESCRIPTION
**Pull request by m-t-a-n-a-k-a**
close #262 
---

Hi there! Thanks so much for submitting a pull request!

Let's just make sure together that all of these boxes are checked before we
merge this change:

- [x] The code in these changes works correctly.
- [x] Code has tests as appropriate.
- [x] Code has been reviewed by @JacobEvelyn.
- [x] All tests pass on Travis CI.
- [x] Code coverage remains high.
- [x] Rubocop reports no issues on Travis CI.
- [x] The `README.md` file is updated as appropriate.

Don't worry—this list will get checked off in no time!

### CODE REVIEW

File: test/commands/remove/tag_spec.rb [hunk 1]
```diff
@@ -7,6 +7,14 @@
 
   let(:content) { CONTENT }
 
+  describe "when friend name and tag are blank" do
+    subject { run_cmd("remove tag") }
```
Comment (JacobEvelyn) [inline test/commands/remove/tag_spec.rb:11]: Would you mind changing this to set `friend_name` and `tag` to `nil` or `""` instead of overwriting the `subject`? Or does that not work?

File: bin/friends [hunk 2]
```diff
@@ -34,6 +34,7 @@ class Tag
   # conversions for arguments.
   # See: https://github.com/davetron5000/gli/issues/241
   def self.convert_to_tag(str)
+    str ||= ""
```
Comment (JacobEvelyn) [inline bin/friends:37]: Would you be open to combining this and the below line into just:

```ruby
str = str.to_s.strip
```

?

**Comment by JacobEvelyn** [comment]
Thanks so much for fixing this, @m-t-a-n-a-k-a! Your fix is now released in version 0.52! 🎉
