### PR TITLE
Fix for the case of add tag or add nickname args are nill

### LINKED ISSUE #265: undefined method error occurred when “add tag" or “add nickname” executed with no arguments
VERSION
 0.52（ruby 2.6.0）

SUMMARY
 When “add tag" or “add nickname” executed with no arguments, undefined method error messages are output as below.

```
$ friends add activity
2020-06-22: test
Activity added: "2020-06-22: test"
$ friends add note
2020-06-22: test
Note added: "2020-06-22: test"
$ friends add friend
Error: Expected "[Friend Name]"
$ friends add tag
Error: undefined method `strip' for nil:NilClass ⬅︎ ★
$ friends add location
Error: Expected "[Location Name]"
$ friends add nickname
Error: undefined method `strip' for nil:NilClass ⬅︎ ★
```

I think it would be better to change the error message as below.
```
$ friends add tag
Error: Expected "[Friend Name] [Tag]”
$ friends add nickname
Error: Expected "[Friend Name] [Nickname]”
```

Could you please let me know what you think about this change?
Thank you.

### PR DESCRIPTION
**Pull request by m-t-a-n-a-k-a**
close #265 
---

I'm not sure if this is the best fix in terms of where throwing exceptions.
Please tell me your opinion🙏
Thank you.

---

Hi there! Thanks so much for submitting a pull request!

Let's just make sure together that all of these boxes are checked before we
merge this change:

- [x] The code in these changes works correctly.
- [x] Code has tests as appropriate.
- [x] Code has been reviewed by @JacobEvelyn.
- [x] All tests pass on Travis CI.
- [x] Code coverage remains high.
- [x] Rubocop reports no issues on Travis CI.
- [x] The `README.md` file is updated as appropriate.

Don't worry—this list will get checked off in no time!

### CODE REVIEW

File: lib/friends/introvert.rb [hunk 1]
```diff
@@ -203,7 +203,11 @@ def rename_location(old_name:, new_name:)
     # @param nickname [String] the nickname to add to the friend
     # @raise [FriendsError] if 0 or 2+ friends match the given name
     def add_nickname(name:, nickname:)
-      raise FriendsError, "Nickname cannot be blank" if nickname.empty?
+      if nickname.empty?
```
Comment (JacobEvelyn) [inline lib/friends/introvert.rb:206]: Do we need these conditionals to be nested, or could we just do this?

```ruby
raise FriendsError, "Expected \"[Friend Name]\" \"[Nickname]\"" if name.empty?
raise FriendsError, "Nickname cannot be blank" if nickname.empty?
```

File: lib/friends/introvert.rb [hunk 2]
```diff
@@ -216,7 +220,11 @@ def add_nickname(name:, nickname:)
     # @param tag [String] the tag to add to the friend, of the form: "@tag"
     # @raise [FriendsError] if 0 or 2+ friends match the given name
     def add_tag(name:, tag:)
-      raise FriendsError, "Tag cannot be blank" if tag == "@"
+      if tag == "@"
```
Comment (JacobEvelyn) [inline lib/friends/introvert.rb:223]: Same question here—do we need these conditionals to be nested or could we just do this?

```ruby
raise FriendsError, "Expected \"[Friend Name]\" \"[Tag]\"" if name.empty?
raise FriendsError, "Tag cannot be blank" if tag == "@"
```

File: test/commands/add/nickname_spec.rb [hunk 3]
```diff
@@ -7,6 +7,15 @@
 
   let(:content) { CONTENT }
 
+  describe "when friend name and nickname are blank" do
```
Comment (JacobEvelyn) [inline test/commands/add/nickname_spec.rb:10]: Just to double-check: my read is that we need both of these to be blank because if only one is blank we'll just be repeating the `"when nickname is blank"` test below. Is that right?

File: test/commands/add/tag_spec.rb [hunk 4]
```diff
@@ -7,6 +7,15 @@
 
   let(:content) { CONTENT }
 
+  describe "when friend name and tag are blank" do
```
Comment (JacobEvelyn) [inline test/commands/add/tag_spec.rb:10]: Same comment here: my read is that we need both of these to be blank because if only one is blank we'll just be repeating the `"when tag is blank"` test below. Is that right?

File: lib/friends/introvert.rb (hunk 1 above)
Comment (m-t-a-n-a-k-a) [reply lib/friends/introvert.rb:206]: Thanks for your comment!
I implemented like this because I thought it would emphasize that “Expected "[Friend Name]" "[Nickname]"” error is raised when neither of the two arguments are present.
However, this is just a subjective idea, so your idea may be better in terms of the more objective aspect of nesting depth.

File: lib/friends/introvert.rb (hunk 2 above)
Comment (m-t-a-n-a-k-a) [reply lib/friends/introvert.rb:223]: I'm thinking about this one as well as the point made to add_nickname🙂

File: test/commands/add/nickname_spec.rb (hunk 3 above)
Comment (m-t-a-n-a-k-a) [reply test/commands/add/nickname_spec.rb:10]: Yes, I implemented it with that intention.

File: test/commands/add/tag_spec.rb (hunk 4 above)
Comment (m-t-a-n-a-k-a) [reply test/commands/add/tag_spec.rb:10]: Yes, I implemented it with that intention.

File: lib/friends/introvert.rb (hunk 1 above)
Comment (JacobEvelyn) [reply lib/friends/introvert.rb:206]: Thanks for explaining your thought process, @m-t-a-n-a-k-a! I have a preference for the change I suggested, in part because I actually think it's important that this code catches the widest possible error case.

This method shouldn't need to know that `name` is, in reality, always going be blank when `nickname` is also blank. If we later changed [the code that calls this](https://github.com/JacobEvelyn/friends/blob/main/lib/friends/commands/add.rb#L38), or added another call site, so that it could sometimes call:

```ruby
add_nickname(name: "", nickname: "not empty")
```

we'd still want to display an error because it's not clear what we'd want the method to do in that case.

Does that make sense?

Comment (m-t-a-n-a-k-a) [reply lib/friends/introvert.rb:206]: I get what you mean. I didnt realize that case.
Indeed, it's obvious when that case inserted and run and we compare the results.
```
$ cat lib/friends/commands/add.rb | grep "@introvert.add_nickname" 
      @introvert.add_nickname(name: "", nickname: "not empty")
      #@introvert.add_nickname(name: args.first.to_s.strip, nickname: args[1].to_s.strip)
```

```
#nested (my fix)
$ bundle exec ruby bin/friends add nickname
Error: No friend found for ""
```
```
#not nested (your idea)
$ bundle exec ruby bin/friends add nickname
Error: Expected "[Friend Name]" "[Nickname]"
```
I'll fix and push again later👍

**Comment by JacobEvelyn** [comment]
Thank you, @m-t-a-n-a-k-a! This change is now released in version 0.53!
